# Generated by Django 2.2.7 on 2019-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_book_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='book',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
