# Generated by Django 2.2.7 on 2019-11-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_auto_20191114_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(storage='book_image', upload_to='default.jpg'),
        ),
    ]
