# Generated by Django 2.2.7 on 2019-11-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_auto_20191115_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book_image/default.jpg', upload_to='book_image'),
        ),
    ]
