# Generated by Django 2.2.7 on 2019-11-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20191115_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
